services:
  - type: static
    name: Flutter_Play_Web
    repo: https://github.com/JosePablo1996/Flutter_Play_Web
    branch: master
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html